'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ParamFields

   '''<summary>
   '''dgRetention control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents dgRetention As Global.System.Web.UI.WebControls.GridView

   '''<summary>
   '''lblBranch control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblBranch As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''dgBranches control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents dgBranches As Global.System.Web.UI.WebControls.GridView

   '''<summary>
   '''lnkNew control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lnkNew As Global.System.Web.UI.WebControls.LinkButton

   '''<summary>
   '''hdParamID control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdParamID As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdFieldID control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdFieldID As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''Panel1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

   '''<summary>
   '''txtDescription control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''vtxtValue2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents vtxtValue2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

   '''<summary>
   '''cvtxtDescription1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents cvtxtDescription1 As Global.System.Web.UI.WebControls.CustomValidator

   '''<summary>
   '''chkInactive control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents chkInactive As Global.System.Web.UI.WebControls.CheckBox

   '''<summary>
   '''btnSave control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnReset control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button
End Class
