'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PaymentPeriods

   '''<summary>
   '''lblmsg control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblmsg As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''txtCode control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtCode As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''vtxtValue0 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents vtxtValue0 As Global.System.Web.UI.WebControls.RequiredFieldValidator

   '''<summary>
   '''cvtxtDescription0 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents cvtxtDescription0 As Global.System.Web.UI.WebControls.CustomValidator

   '''<summary>
   '''txtDescription control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''vtxtValue2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents vtxtValue2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

   '''<summary>
   '''cvtxtDescription1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents cvtxtDescription1 As Global.System.Web.UI.WebControls.CustomValidator

   '''<summary>
   '''txtInterestRate control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtInterestRate As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''cvtxtDescription2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents cvtxtDescription2 As Global.System.Web.UI.WebControls.CustomValidator

   '''<summary>
   '''txtPaymentDays control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtPaymentDays As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''cvtxtDescription3 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents cvtxtDescription3 As Global.System.Web.UI.WebControls.CustomValidator

   '''<summary>
   '''txtPaymentMonths control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtPaymentMonths As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''cvtxtDescription4 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents cvtxtDescription4 As Global.System.Web.UI.WebControls.CustomValidator

   '''<summary>
   '''chkInactive control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents chkInactive As Global.System.Web.UI.WebControls.CheckBox

   '''<summary>
   '''btnSave control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnReset control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''dgRetention control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents dgRetention As Global.System.Web.UI.WebControls.GridView
End Class
